### ISSUE TITLE
Ticket 1a - Header component

### ISSUE THREAD

**Issue by AndrianaOS** [Gayle-Thompson-Igwebike/GOOD-PR-v1#1]
| name  | about | title  | labels | assignees  |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| "👥 User story"  | Create a new user story  | Brand Logo  | New feature  | George  | 

## Story

- **As a** user

- **I Want** I want to see a company logo

- **So That** I know what company this website is associated with. 

## Acceptance Criteria

1. Given I arrive at  the Tracker App
   - When I look at the header,
   - Then I should be able to see a company logo associated to the same website
2. Given .............
   - When .............
   - Then .............

## Implementation Notes

1.
2.

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by GeorgePrimentas** [comment]
Pull Request Link: https://github.com/Gayle-Thompson-Igwebike/GOOD-PR-v1/compare/Header?expand=1
