### ISSUE TITLE
Traffic Light Buttons - (Links to clickable cards issue)

### ISSUE THREAD

**Issue by Gayle-Thompson-Igwebike** [Gayle-Thompson-Igwebike/GOOD-PR-v1#8]
| name  | about | title  | labels | assignees  |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| "👥 User story"  | Create a new user story  | “TICKET 6”  | Traffic Light Buttons display | Andriana  | 

**## Story: Traffic Light Buttons display on landing page**

- *As a ….user,

- **I want to….. see buttons in traffic light order

- *So That ….. I can see at a glance, which teams are in danger (red)

**## Acceptance Criteria**

1.GIVEN ... I arrive on the apps landing page
- WHEN ...I see cards displayed in a traffic light format
- THEN ...I should be able tot ell which team are in danger of failing their PR contributions

2. Given .............
   - When .............
   - Then .............

## Implementation Notes

1.
2.

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by SagharHosseinmardi** [comment]
PR link: https://github.com/Gayle-Thompson-Igwebike/GOOD-PR-v1/pull/44
